title: Sebastian Wiesner
description: >-
  System engineer for satellite mission planning. Gnome. Rust. Arch.
repository: swsnr/swsnr.de
url: "https://swsnr.de"
excerpt_separator: "<!--more-->"
show_excerpts: true
timezone: UTC
permalink: /:slug
theme: minima

include:
  - .well-known

# See https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
author:
  name: Sebastian Wiesner
  email: sebastian@swsnr.de
logo: /assets/avatar.jpg
social:
  name: Sebastian Wiesner
  links:
    - https://github.com/swsnr
    - https://mastodon.social/@swsnr
    - https://matrix.to/#/@swsnr:matrix.org
    - https://www.linkedin.com/in/swsnr/
    - https://build.opensuse.org/users/swsnr

# See https://github.com/benbalter/jekyll-relative-links#configuration
relative_links:
  enabled: true
  # Required to make relative links to posts work
  collections: true

# See https://github.com/benbalter/jekyll-titles-from-headings#configuration
titles_from_headings:
  enabled: true
  # Strip title from rendered body to avoid having it appear twice in minima,
  # which also shows page.title in its layouts
  strip_title: true
  collections: true

# See https://github.com/jekyll/minima#usage
header_pages:
  # Show pages in header navigation
  - about.md
  - privacy.md
disqus:
  # We're overriding the disqus theme to use a different commenting solution,
  # so we just use any truthy value here to make minima include the comment template.
  shortname: true
minima:
  skin: swsnr-bw-auto
  # Social links for the footer
  social_links:
    - platform: github
      user_url: "https://github.com/swsnr"
    - platform: obs
      user_url: https://build.opensuse.org/users/swsnr
    - platform: mastodon
      user_url: "https://mastodon.social/@swsnr"
    - platform: matrix
      user_url: "https://matrix.to/#/@swsnr:matrix.org"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/swsnr/"

# See https://github.com/jekyll/jekyll-feed#usage
feed:
  categories:
    - archlinux
    - gnome

markdown: CommonMark
commonmark:
  options: [FOOTNOTES, UNSAFE]
  extensions: [table, autolink, strikethrough]
