title: Sebastian Wiesner
description: >-
  System engineer for satellite mission planning. Gnome. Rust. Arch.
repository: swsnr/swsnr.de
url: "https://swsnr.de"
excerpt_separator: "<!--more-->"
show_excerpts: true
timezone: UTC
permalink: /:slug
theme: minima

author:
  name: Sebastian Wiesner
  email: sebastian@swsnr.de

relative_links:
  enabled: true
  collections: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

header_pages:
  - colophon.md
  - privacy.md

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/swsnr"
    - platform: mastodon
      user_url: "https://mastodon.social/@swsnr"
    - platform: matrix
      user_url: "https://matrix.to/#/@swsnr:matrix.org"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/swsnr/"

feed:
  tags: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  gfm_quirks: [no_auto_typographic]
  auto_id_stripping: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
