title: Basti
description: >-
  Scala software developer. System engineer satellite mission planning. Rust. Arch.
repository: swsnr/swsnr.de
url: 'https://swsnr.de'
excerpt_separator: "<!--more-->"
show_excerpts: true
timezone: UTC
permalink: date

author:
  name: Basti
  email: sebastian@swsnr.de

relative_links:
  enabled:     true
  collections: true

feed:
  tags: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  gfm_quirks: [no_auto_typographic]
  auto_id_stripping: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
