name: Deploy site

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  DENO_DIR: ./.deno-cache

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno task build
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "_site"
      - uses: actions/deploy-pages@v1
