name: Deploy site

on:
  push:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow to write to deployments
permissions:
  contents: read
  id-token: write

env:
  DENO_DIR: ./.deno-cache

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Enable drafts unless deploying main
        run: echo "LUME_DRAFTS=true" >>"${GITHUB_ENV}"
        if: github.ref_name != 'main'
      - name: Set production environment
        run: echo "SWSNR_ENVIRONMENT=production" >>"${GITHUB_ENV}"
        if: github.ref_name == 'main'
      - run: deno task build
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "swsnr"
          entrypoint: "serve.ts"
          root: ""
          exclude: |
            .deno-cache/
