name: Deploy site

on:
  push:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  DENO_DIR: ./.deno-cache

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - run: deno task build
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "swsnr"
          entrypoint: "serve.ts"
          root: ""
          exclude: |
            .deno-cache/
